# Generated by Django 2.1.5 on 2019-02-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='anime',
            new_name='name',
        ),
    ]
