# Generated by Django 2.1.5 on 2019-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190209_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoitemdesc',
            name='info_item_name',
        ),
        migrations.RenameField(
            model_name='infoitem',
            old_name='name',
            new_name='info_name',
        ),
        migrations.RenameField(
            model_name='shortinfoaboutcompany',
            old_name='text',
            new_name='text_about',
        ),
        migrations.AddField(
            model_name='infoitem',
            name='info_description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InfoItemDesc',
        ),
    ]
