# Generated by Django 2.1.5 on 2019-02-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190209_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('short_desc', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Спец. Услуга',
                'verbose_name_plural': 'Спец. Услуги',
            },
        ),
        migrations.CreateModel(
            name='SpecialServiceWorksNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=50)),
                ('min_price', models.SmallIntegerField()),
                ('count', models.SmallIntegerField()),
                ('units', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Наименование спец. работы',
                'verbose_name_plural': 'Наименование спец. работ',
            },
        ),
        migrations.AlterModelOptions(
            name='infoitem',
            options={'verbose_name': 'Пункт информации', 'verbose_name_plural': 'Пукнты информации'},
        ),
        migrations.AlterModelOptions(
            name='orderrequest',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='serviceworksnames',
            options={'verbose_name': 'Наименование работы', 'verbose_name_plural': 'Наименование работ'},
        ),
        migrations.AlterModelOptions(
            name='shortinfoaboutcompany',
            options={'verbose_name': 'Краткая информация о компании', 'verbose_name_plural': 'Краткая информация о компании'},
        ),
        migrations.AlterModelOptions(
            name='whywe',
            options={'verbose_name': 'Почему мы', 'verbose_name_plural': 'Почему мы'},
        ),
        migrations.AddField(
            model_name='specialserviceworksnames',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Service', to_field='name'),
        ),
    ]
