# Generated by Django 2.1.5 on 2019-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190228_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewer_photo',
            field=models.ImageField(upload_to='images/review', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='image_for_description',
            field=models.ImageField(upload_to='images/whywe/description', verbose_name='Фон для описания'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='image_for_name',
            field=models.ImageField(upload_to='images/whywe/name', verbose_name='Фон для названия'),
        ),
    ]
