# Generated by Django 2.1.5 on 2019-02-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190222_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.AddField(
            model_name='reviews',
            name='first_name',
            field=models.CharField(default='empty', max_length=20, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='last_name',
            field=models.CharField(default='empty', max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='infoitem',
            name='info_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='infoitem',
            name='info_name',
            field=models.CharField(default='empty', max_length=20, unique=True, verbose_name='Достоинство'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='email',
            field=models.CharField(default='empty', max_length=20, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='name',
            field=models.CharField(default='empty', max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='phone',
            field=models.CharField(default='empty', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='empty', max_length=30, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_desc',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='serviceworksnames',
            name='min_price',
            field=models.SmallIntegerField(verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='serviceworksnames',
            name='work_title',
            field=models.CharField(default='empty', max_length=50, verbose_name='Наименование работы'),
        ),
        migrations.AlterField(
            model_name='shortinfoaboutcompany',
            name='text_about',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='name',
            field=models.CharField(default='empty', max_length=40, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='short_desc',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='specialserviceworksnames',
            name='count',
            field=models.SmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='specialserviceworksnames',
            name='min_price',
            field=models.SmallIntegerField(verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='specialserviceworksnames',
            name='units',
            field=models.CharField(default='empty', max_length=10, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='specialserviceworksnames',
            name='work_title',
            field=models.CharField(default='empty', max_length=50, verbose_name='Наименование работы'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='description',
            field=models.TextField(verbose_name='Описание элемента'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='name',
            field=models.CharField(default='empty', max_length=30, verbose_name='Название элемента'),
        ),
    ]
