# Generated by Django 2.1.5 on 2019-02-25 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190226_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата заказа'),
            preserve_default=False,
        ),
    ]
