# Generated by Django 2.1.5 on 2019-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoitem',
            name='info_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Достоинство'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='serviceworksnames',
            name='work_title',
            field=models.CharField(max_length=50, verbose_name='Наименование работы'),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='specialserviceworksnames',
            name='units',
            field=models.CharField(max_length=10, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='specialserviceworksnames',
            name='work_title',
            field=models.CharField(max_length=50, verbose_name='Наименование работы'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название элемента'),
        ),
    ]
