# Generated by Django 2.1.5 on 2019-02-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0003_remove_flatpage_keks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('kek', models.IntegerField(verbose_name='something')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
