# Generated by Django 2.1.5 on 2019-02-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=20, unique=True)),
                ('info_description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpage_main.MyFlatPage')),
            ],
        ),
    ]
