# Generated by Django 2.1.5 on 2019-02-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage_main', '0002_infoitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoitems',
            name='page',
        ),
        migrations.RemoveField(
            model_name='myflatpage',
            name='kek',
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='desc_items',
            field=models.TextField(blank=True, verbose_name='Description items'),
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='InfoItems',
        ),
    ]
